In [1]:
import numpy as np

In [2]:
g = 2

In [3]:
entradas = np.array(object=[1, 2, 3])
entradas

array([1, 2, 3])

In [4]:
saidas = np.array(object=[6, 12, 20])
saidas

array([ 6, 12, 20])

In [5]:
matriz_coefs = np.zeros(shape=(g+1, g+1))
matriz_coefs

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
matriz_resultados = np.zeros(shape=g + 1)
matriz_resultados

array([0., 0., 0.])

In [7]:
matriz_somatorios = np.zeros(shape=2 * g + 1)
matriz_somatorios

array([0., 0., 0., 0., 0.])

In [10]:
for i in range(2 * g + 1, 0, -1):
    
    # print(i - 1)
    print(entradas ** (i - 1))

[ 1 16 81]
[ 1  8 27]
[1 4 9]
[1 2 3]
[1 1 1]


In [15]:
for i in range(2 * g, -1, -1):
    # print(i)
    # print(entradas ** i)
    # print((entradas ** i).sum())
    matriz_somatorios[i] = (entradas ** i).sum()

matriz_somatorios

array([ 3.,  6., 14., 36., 98.])

In [16]:
matriz_somatorios[::-1]

array([98., 36., 14.,  6.,  3.])

In [17]:
matriz_somatorios = matriz_somatorios[::-1]
matriz_somatorios

array([98., 36., 14.,  6.,  3.])

In [22]:
for i in range(0, g + 1, 1):
    # print(i)
    # print(matriz_somatorios[i:i + g + 1])

    matriz_coefs[i, :] = matriz_somatorios[i:i + g + 1]

matriz_coefs

array([[98., 36., 14.],
       [36., 14.,  6.],
       [14.,  6.,  3.]])

In [26]:
for i in range(0, g + 1, 1):
    # print(i)
    array_x = entradas ** i
    array_y = saidas ** 1
    # print(array_x)
    # print(array_y)
    # print("-" * 100)
    array_mult = array_x * array_y
    somatoria = array_mult.sum()

    matriz_resultados[i] = somatoria

matriz_resultados

array([ 38.,  90., 234.])

In [27]:
matriz_resultados = matriz_resultados[::-1]
matriz_resultados

array([234.,  90.,  38.])

In [30]:
matriz_coefs_inv = np.linalg.inv(matriz_coefs)
matriz_coefs_inv

array([[  1.5,  -6. ,   5. ],
       [ -6. ,  24.5, -21. ],
       [  5. , -21. ,  19. ]])

In [31]:
matriz_coefs_inv.dot(matriz_resultados)

array([1., 3., 2.])

In [32]:
def mmq(entradas: np.ndarray,
        saidas: np.ndarray,
        g:int) -> np.ndarray:
    
    """
    Função que calcula o método dos mínimos quadrados para um polinômio de grau 'g'.

    Args:
    entradas (np.ndarray): Array de entradas do polinômio que se deseja ajustar.
    saidas (np.ndarray): Array de saídas do polinômio que se deseja ajustar.
    g (int): Grau do polinômio que se deseja ajustar.

    Returns:
    np.ndarray: Array com os coeficientes do polinômio ajustado.
    (a, b, c, ...)
    """
    
    if g < 1:
        raise Exception(f"Não é possível usar o mmq para g < 0. {g}")
    
    if not isinstance(g, int):
        raise Exception(f"O objeto no parametro 'g' deve ser um 'int'. Foi fornecido um objeto do tipo {type(g)}")
    
    matriz_coefs = np.zeros(shape=(g+1, g+1))
    matriz_resultados = np.zeros(shape=g + 1)
    matriz_somatorios = np.zeros(shape=2 * g + 1)

    for i in range(2 * g, -1, -1):
        matriz_somatorios[i] = (entradas ** i).sum()

    matriz_somatorios = matriz_somatorios[::-1]

    for i in range(0, g + 1, 1):
        matriz_coefs[i, :] = matriz_somatorios[i:i + g + 1]

    for i in range(0, g + 1, 1):
        array_x = entradas ** i
        array_y = saidas ** 1
        array_mult = array_x * array_y
        somatoria = array_mult.sum()

        matriz_resultados[i] = somatoria
    
    matriz_resultados = matriz_resultados[::-1]
    matriz_coefs_inv = np.linalg.inv(matriz_coefs)

    coefs = matriz_coefs_inv.dot(matriz_resultados)

    return coefs

In [33]:
mmq(entradas=entradas, saidas=saidas, g=2)

array([1., 3., 2.])