In [1]:
import statistics
import math
from mmq import metodo_minimos_quadrados
import numpy as np

In [ ]:
print("hurst")

In [2]:
serie_dados = [1, 4, 9, 8, 5, 0, 2, 6, 8, 4, 5]
serie_dados

[1, 4, 9, 8, 5, 0, 2, 6, 8, 4, 5]

In [3]:
serie_dados[2]

9

In [5]:
sequencia_N = [2, 4, 8, 11]
sequencia_N

[2, 4, 8, 11]

In [6]:
serie_dominus = []
serie_functus = []
for N in sequencia_N:
    # print(serie_dados[:N])

    dados = serie_dados[:N]
    # print(dados)

    media_N = statistics.mean(dados)
    dp_N = statistics.pstdev(dados)

    # print(media_N, dp_N)

    colecao_y = [0]
    for n in range(N):
        # print(n, dados[n])
        subtracao = dados[n] - media_N
        y = subtracao + colecao_y[-1]
        colecao_y.append(y)
    
    # print(colecao_y)
    # print("-" * 100)

    colecao_y.pop(0)
    # print(colecao_y)

    max_y = max(colecao_y)
    min_y = min(colecao_y)
    range_N = max_y - min_y

    # print(range_N)

    log_N = math.log2(N)
    log_r_dp = math.log2(range_N / dp_N)

    # print(log_N, log_r_dp)

    serie_dominus.append(log_N)
    serie_functus.append(log_r_dp)

print(serie_dominus)
print(serie_functus)

[1.0, 2.0, 3.0, 3.4594316186372973]
[0.0, 0.9061864984121143, 1.5462399594159157, 1.4818931302529683]


In [7]:
arr_dominus = np.array(serie_dominus)
arr_functus = np.array(serie_functus)

In [14]:
arr_dominus

array([1.        , 2.        , 3.        , 3.45943162])

In [9]:
arr_functus

array([0.        , 0.9061865 , 1.54623996, 1.48189313])

In [13]:
coefs = metodo_minimos_quadrados.mmq(
    arr_dominus,
    arr_functus,
    1)

coefs

array([ 0.63197281, -0.51094599])

In [15]:
print(f"O coeficiente de Hurst é: {coefs[0]}")

O coeficiente de Hurst é: 0.631972808594316


In [16]:
def gerar_sequencia_N(serie_dados):
    
    comprimento_lista = len(serie_dados)
    
    sequencia_N = []
    
    valor = 2
    
    while valor <= comprimento_lista:
        sequencia_N.append(valor)
        valor *= 2
    
    if max(sequencia_N) < comprimento_lista:
        sequencia_N.append(comprimento_lista)
    
    return sequencia_N

In [19]:
gerar_sequencia_N(serie_dados=np.array([2, 7, 1, 7, 2, 5, 8, 5, 3]))

[2, 4, 8, 9]

In [48]:
def hurst(serie_dados: list | np.ndarray) -> float:
    """
    Esta função calcula o coeficiente de aleatoriedade da series
    de dados fornecida no parametro 'serie_dados'.

    param.:
    series_dados: serie para calcular o coef. de aleatoriedade

    return:
    esta funcao retorna uma objeto do tipo float que representa a alea
    """

    sequencia_N = gerar_sequencia_N(serie_dados)
    
    serie_dominus = []
    serie_functus = []
    for N in sequencia_N:
        dados = serie_dados[:N]
        
        media_N = statistics.mean(dados)
        dp_N = statistics.pstdev(dados)

        if dp_N == 0:
            continue

        colecao_y = [0]
        for n in range(N):
            subtracao = dados[n] - media_N
            y = subtracao + colecao_y[-1]
            colecao_y.append(y)

        colecao_y.pop(0)

        max_y = max(colecao_y)
        min_y = min(colecao_y)
        range_N = max_y - min_y

        log_N = math.log2(N)
        log_r_dp = math.log2(range_N / dp_N)

        serie_dominus.append(log_N)
        serie_functus.append(log_r_dp)

    if serie_dominus == [] or serie_functus == []:
        return 1

    if len(serie_dominus) == 1 or len(serie_functus) == 1:
        raise Exception("""Sua série de dados possui muito pouca variação
                            de dados. Somente um ponto foi gerado""")

    arr_dominus = np.array(serie_dominus)
    arr_functus = np.array(serie_functus)

    coefs = metodo_minimos_quadrados.mmq(
        arr_dominus,
        arr_functus,
        1)
    
    return coefs[0]

In [53]:
hurst([2, 5, 8, 3, 2])

0.8442306028037387