In [1]:
import numpy as np

## Diferença entre funções e métodos em python (apenas o básico)

Funções em python são definidas usando a palavra chave `def`. A sintaxe é a seguinte:
````python
def elevado(base, exponente):
    valor_retornar = base ** exponente
    return valor_retornar
````

Métodos em python são definidos dentro de objetos (classes). A sintaxe é a seguinte:
````python
# A classe é algo como uma fábrica de objetos
class Potencias:
    # Este é um construtor (do objeto) - O objeto será da classe Potencias
    def __init__(self, base):

        # Este é um atributo/propriedade
        self.base = base

    # Este é um método (É uma função dentro do objeto/classe)
    def elevado(self, exponente):
        return self.base ** exponente
````


````python	
# Usando a função ----------------------------
# retornaria 8
elevado(base=2, exponente=3) 
# --------------------------------------------


# Usando o método ----------------------------
# Criando um objeto da classe Potencias
potencia = Potencias(base=2)

# O primeiro argumento do método é sempre o próprio objeto
potencia.elevado(exponente=3) # Retornaria 8
# --------------------------------------------
````

In [1]:
def elevado(base, exponente):
    valor_retornar = base ** exponente
    return valor_retornar

In [2]:
resultado = elevado(base=2, exponente=3)
print(resultado)

8


In [37]:
class Potencias:
    # o construtor é chamado quando a classe instancia um objeto.
    # ele deve ser preenchido com as propriedades que o objeto deve ter.
    def __init__(x, base):
        x.base = base
        
    # este é um método da classe, que pode ser chamado por qualquer objeto
    def elevado(self, expoente):
        return self.base ** expoente
    
    def __pow__(self, expoente):
        return self.base + expoente
    
    def __repr__(self):
        return f"A base deste objeto é: {self.base}"

In [38]:
# Criando o objeto da classe Potencias. O objeto abaixo tem como atributo base o valor 2.
potencia = Potencias(base=2)

In [39]:
# Criando o objeto da classe Potencias. O objeto abaixo tem como atributo base o valor 3.
potencia_um = Potencias(base=3)

In [40]:
# No objeto abaixo, note que existe o atributo 'base' e o método 'elevado'.
print(dir(potencia))    # or print(dir(Potencias))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__pow__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'base', 'elevado']


In [41]:
# Abaixo, o objeto potencia tem como atributo 'base' o valor 2. O método 'elevado' recebe como parâmetro 'expoente' o valor 3.
# O método elevado retorna o valor 2 elevado a 3 (2³=8).
potencia.elevado(expoente=3)

8

In [42]:
# Abaixo, o objeto potencia1 tem como atributo 'base' o valor 3. O método 'elevado' recebe como parâmetro 'expoente' o valor 3.
# O método elevado retorna o valor 3 elevado a 3 (3³=27).
potencia_um.elevado(expoente=3)

27

In [43]:
dir(potencia) # ou dir(Potencias)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__pow__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'base',
 'elevado']

In [44]:
# o comando abaixo chama o método especial '__eq__'
# como não programamos esse método ele retorna um valor padrão
potencia == potencia_um

False

In [45]:
# o operador ** é um atalho para o método 'mágico'
# __pow__ da classe Potencias.
# 2 (potencia.base) + 3 = 5
potencia ** 3

5

In [46]:
print(potencia)

A base deste objeto é: 2


In [47]:
print(potencia_um)

A base deste objeto é: 3


### potencia é um objeto da classe Potencias (criamos um novo tipo de variável)

---

In [49]:
import numpy as np

In [ ]:
# numpy main usages
# 1: np.array([1, 2, 3])
# 2: np.array([1, 2, 3], dtype=np.float32)                  # convert to numpy array with float32
# 3: np.array([1, 2, 3], dtype=np.float32).dtype            # check the type of the array
# 4: np.array([1, 2, 3], dtype=np.float32).shape            # check the shape of the array
# 5: np.array([1, 2, 3], dtype=np.float32).ndim             # check the number of dimensions of the array
# 6: np.array([1, 2, 3], dtype=np.float32).size             # check the size of the array
# 7: np.array([1, 2, 3], dtype=np.float32).itemsize         # check the size of each item of the array
# 8: np.array([1, 2, 3], dtype=np.float32).nbytes
# 9: np.array([1, 2, 3], dtype=np.float32).data
# 10: np.array([1, 2, 3], dtype=np.float32).data.obj

In [50]:
arr = np.ndarray(shape=(3, 4), dtype=int)
arr

array([[384737792,       613, 384738464,       613],
       [384739216,       613, 384739216,       613],
       [384739216,       613, 384729504,       613]])

In [51]:
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista2d = [[1, 2, 3], 
           [4, 5, 6]]

In [52]:
# convertendo o objeto 'lista' num objeto 'numpy.array'
arr = np.array(lista1, dtype=int)
arr

array([1, 2, 3])

In [53]:
# um array possui 70 métodos/propriedades
print(dir(arr)[96:])

['all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']


# Atributos do objeto **array**
### **Arrays Numpy** são mais similares a vetores/matriz matemáticos!!!

In [ ]:
# Principais propriedades (características) de um array numpy
# 1: arr.ndim
# 2: arr.shape
# 3: arr.size
# 4: arr.dtype
# 5: arr.nbytes

In [54]:
numpy_array = np.array(lista1, dtype=int)
numpy_array2d = np.array(lista2d, dtype=int)

# o print de um objeto 'numpy array' é diferente do print de uma lista (embora pareça igual)
# note a falta das vírgulas entre os elementos do array
print(numpy_array)
print()
print(numpy_array2d)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [55]:
# 1 porpriedade: ndim
print(numpy_array.ndim)         # returns the number of dimensions of the array: 1

1


In [56]:
# 1 porpriedade: ndim
print(numpy_array2d.ndim)       # returns the number of dimensions of the array: 2

2


In [57]:
# 2 porpriedade: shape
print(numpy_array.shape)        # returns a tuple with the shape of the array: (3,) -> 3 rows, 1 column

(3,)


In [58]:
# 2 porpriedade: shape
print(numpy_array2d.shape)

(2, 3)


In [62]:
# para criar uma tupla com UM elemento, você precisa adicionar uma vírgula após o elemento

print(type([3,]))
print(type((3)))
print(type((3,)))

<class 'list'>
<class 'int'>
<class 'tuple'>


In [63]:
# 3 porpriedade: size
print(numpy_array.size)         # returns the number of elements of the array: 3

3


In [64]:
# 3 porpriedade: size
print(numpy_array2d.size)       # returns the number of elements of the array: 6

6


In [65]:
# 4 porpriedade: dtype
print(numpy_array.dtype)        # returns the type of the elements of the array: int32

int32


## É importante saber disso porque isso afetará o uso da memória do array

In [ ]:
# limites de um int32: -2.147.483.648 to 2.147.483.647            ou -2**31 até 2**31 - 1
# limites de um uint32: 0 to 4.294.967.295                        ou  0     até 2**32 - 1

In [ ]:
# limites de um intk:  -2 ** (k-1) até 2 ** (k-1) - 1
# limites de um uintk: 0           até 2 ** k - 1

In [ ]:
# representação binária de um uint3

# 0 0 0  -> 0
# 0 0 1  -> 1
# 0 1 0  -> 2
# 0 1 1  -> 3
# 1 0 0  -> 4
# 1 0 1  -> 5
# 1 1 0  -> 6
# 1 1 1  -> 7

# representação binária de um int3

# 1 0 0  -> -4
# 1 0 1  -> -3
# 1 1 0  -> -2
# 1 1 1  -> -1
# 0 0 0  -> +0
# 0 0 1  -> +1
# 0 1 0  -> +2
# 0 1 1  -> +3

In [66]:
print(numpy_array.dtype)
numpy_array                     # int32 (4 bytes)

int32


array([1, 2, 3])

In [67]:
# 5 porpriedade: nbytes
print(numpy_array.nbytes)       # returns the number of bytes of the array: 12

12


In [68]:
# 6 propriedade T (transpose/transposta)
numpy_array2d.T          # returns the transpose of the array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
numpy_array2d.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Criando cria-se um array numpy é necessário haver uma **estimativa** do tamanho dos valores que estarão contidos no array
#### Para que na criação do array numpy seja alocado o espaço **necessário** para armazenar os valores!!!
---
## Operações com array

In [72]:
# criando um array numpy declarando que cada elemento será do tipo float com 32 bits (float32)
arr1 = np.array([6, 4, 3], dtype=np.float32)
arr2 = np.array([1, 2, 3], dtype=np.float32)

In [73]:
arr1 * arr2            # multiplicação elemento a elemento

array([6., 8., 9.], dtype=float32)

In [74]:
lista1 * lista2        # multiplicação elemento a elemento

TypeError: can't multiply sequence by non-int of type 'list'

In [75]:
arr1 + arr2            # soma elemento a elemento

array([7., 6., 6.], dtype=float32)

In [76]:
lista1 + lista2        # concatenação de listas

[1, 2, 3, 4, 5, 6]

In [77]:
arr1 / arr2            # divisão elemento a elemento

array([6., 2., 1.], dtype=float32)

In [78]:
arr1 - arr2             # subtração elemento a elemento

array([5., 2., 0.], dtype=float32)

In [79]:
arr1 ** arr2            # potencia elemento a elemento

array([ 6., 16., 27.], dtype=float32)

In [80]:
arr1 // arr2            # divisão inteira elemento a elemento

array([6., 2., 1.], dtype=float32)

In [81]:
arr1 % arr2            # mod (resto da divisão) elemento a elemento

array([0., 0., 0.], dtype=float32)

In [82]:
arr1 > arr2            # comparação elemento a elemento

array([ True,  True, False])

In [85]:
# arr1 > arr2 retorna um array (ver acima)
(arr1 > arr2).any()

True

In [86]:
(arr1 > arr2).all()

False

---
## array slicing

In [15]:
# regras para fatiar um array numpy...
# 1: array[start:end] -> o parametro start é 'inclusivo' e o parametro 'end' é exclusivo
# 2: array[start:] -> start is inclusive and end is the last element
# 3: array[:end] -> start is the first element and end is exclusive
# 4: array[:] -> start is the first element and end is the last element
# 5: array[start:end:step] -> step is the step size

# np.zeros ou no.ones são métodos do numpy para criar arrays numpy com valores específicos. Depois disso, você pode alterar os valores
arr = np.zeros(shape=(10, 10), dtype=int)
for row in range(1, arr.shape[0] + 1):
    for col in range(1, arr.shape[1] + 1):
        arr[row - 1, col - 1] = int(row * col)

arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [88]:
arr.dtype

dtype('int32')

In [94]:
print(arr[0, 0])          # primeiro elemento. Em listas, seria arr[0][0]

1


In [95]:
print(arr[0, -1])         # último elemento da primeira linha. Em listas, seria arr[0][-1]

10


In [96]:
print(arr[-1, 0])         # primeiro elemento da última linha. Em listas, seria arr[-1][0]

10


In [97]:
print(arr[-1, -1])        # último elemento da última linha. Em listas, seria arr[-1][-1]

100


In [98]:
print(arr[0, :])          # primeira linha (0) e todas as colunas (:). Em listas, seria arr[0][:]

[ 1  2  3  4  5  6  7  8  9 10]


In [99]:
print(arr[-1, :])         # última linha (-1) e todas as colunas (:). Em listas, seria arr[-1][:]

[ 10  20  30  40  50  60  70  80  90 100]


In [100]:
print(arr[:, 0])          # todas as linhas (:) e a primeira coluna (0). Em listas, seria arr[:][0]

[ 1  2  3  4  5  6  7  8  9 10]


In [101]:
print(arr[:, -1])         # todas as linhas (:) e a última coluna (-1). Em listas, seria arr[:][-1]

[ 10  20  30  40  50  60  70  80  90 100]


In [103]:
print(arr[0:3, 0:3])      # primeiras 3 linhas e primeiras 3 colunas. Em listas, seria arr[0:3][0:3]

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [107]:
print(arr[:3, :])        # primeiras 3 linhas e todas as colunas. Em listas, seria arr[0:3][:]

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 2  4  6  8 10 12 14 16 18 20]
 [ 3  6  9 12 15 18 21 24 27 30]]


In [108]:
print(arr[:, 0:3])        # todas as linhas e primeiras 3 colunas. Em listas, seria arr[:][0:3]

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]
 [ 9 18 27]
 [10 20 30]]


In [109]:
print(arr[:, :])          # todas as linhas e todas as colunas. Em listas, seria arr[:][:]

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [110]:
print(arr[0:6:2, 2:9:3])        # linhas pares e colunas pares

[[ 3  6  9]
 [ 9 18 27]
 [15 30 45]]


In [111]:
print(arr[1:11:2, 0:11:1])        # linhas ímpares e colunas ímpares

[[  2   4   6   8  10  12  14  16  18  20]
 [  4   8  12  16  20  24  28  32  36  40]
 [  6  12  18  24  30  36  42  48  54  60]
 [  8  16  24  32  40  48  56  64  72  80]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [112]:
print(arr[9:1:-2, 9:0:-1])        # linhas pares e colunas pares invertidas

[[100  90  80  70  60  50  40  30  20]
 [ 80  72  64  56  48  40  32  24  16]
 [ 60  54  48  42  36  30  24  18  12]
 [ 40  36  32  28  24  20  16  12   8]]


In [114]:
# imprimindo a quarta linha (indice 3)
print(arr[3])

# índices: [ 0  1  2  3  4  5  6  7  8  9]
# valores: [ 4  8 12 16 20 24 28 32 36 40]

[ 4  8 12 16 20 24 28 32 36 40]


In [ ]:
# classificando os valores da quarta linha em ordem crescente
print(arr[3][[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print()
# classificando os valores da quarta linha em ordem decrescente
print(arr[3][[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]])

In [121]:
# filtrando os valores da quarta linha com os indices 5, 7, 6, 4, 8
print(arr[3, [5, 7, 6, 4, 8]])

[24 32 28 20 36]


In [122]:
np.random.random(size=(2, 2, 3))

array([[[0.74831625, 0.90289049, 0.07053098],
        [0.70211532, 0.1904878 , 0.02453786]],

       [[0.75930542, 0.25383276, 0.64223637],
        [0.67099676, 0.25971298, 0.81243924]]])

In [123]:
(np.random.random(size=(2, 2, 3)) * 255).astype(np.uint8)

array([[[215,  63,   1],
        [219, 100, 234]],

       [[ 82, 136,  68],
        [ 16,  35, 242]]], dtype=uint8)

In [124]:
imagem = (np.random.random(size=(2, 2, 3)) * 255).astype(np.uint8)
imagem

array([[[ 71,  48, 209],
        [213,   0, 214]],

       [[ 94, 217, 179],
        [ 27, 181,  30]]], dtype=uint8)

In [130]:
# operador ellipsys
imagem[..., 0]      # canal vermelho (mesmo que imagem[:, :, 0])

array([[ 71, 213],
       [ 94,  27]], dtype=uint8)

In [126]:
imagem[..., 1]      # canal verde (mesmo que imagem[:, :, 1])

array([[ 48,   0],
       [217, 181]], dtype=uint8)

In [127]:
imagem[..., 2]      # canal azul (mesmo que imagem[:, :, 2])

array([[209, 214],
       [179,  30]], dtype=uint8)

In [131]:
np.mean(imagem, axis=2).astype(np.uint8)     # média dos 3 canais (imagem em escala de cinza)

array([[109, 142],
       [163,  79]], dtype=uint8)

---
# Métodos de arrays numpy

In [ ]:
# mostrando todos os métodos e propriedades de um array numpy (exceto os métodos especiais)
print(dir(arr1)[96:])

# 'all' está dentro de todos os objetos numpy array (método)
# 'any' está dentro de todos os objetos numpy array (método)
# 'argmax' está dentro de todos os objetos numpy array (método)
# ...

In [ ]:
# Métodos mais utilizados de um array numpy
# 1: array.argmax
# 2: array.argmin
# 3: array.argsort
# 4: array.max
# 5: array.min
# 6: array.mean
# 7: array.std
# 8: array.sum
# 9: array.var
# 10: array.reshape
# 11: array.ravel
# 12: array.unique
# 13: np.random.randint
# 14: np.random.randn
# 15: np.random.choice
# 16: np.arange
# 17: np.random.shuffle
# 18: np.random.seed
# 19: np.concatenate
# 20: np.where
# 21: np.linspace

In [1]:
# função usada apenas para criar arrays aleatórios
def criar_array_aleatorio(rows, cols):
    return np.random.randint(0, 100, size=(rows, cols))     # cria um array numpy com valores aleatórios entre 0 e 100

---

# 1: array.argmax

In [4]:
arr1 = criar_array_aleatorio(3, 4)
arr1

array([[93, 37, 34, 66],
       [ 4, 25, 89, 18],
       [84, 55,  6, 51]])

In [5]:
# arr1.argmax(axis=0) = [indmax da coluna 0 | indmax da coluna 1 | indmax da coluna 2 | indmax da coluna 3]
# arr1.argmax(axis=1) = [indmax da linha 0 | indmax da linha 1 | indmax da linha 2]

print(arr1.argmax(axis=0))             # retorna o índice do maior valor do array considerando o eixo 0 (linhas)
print()
print(arr1.argmax(axis=1))             # retorna o índice do maior valor do array considerando o eixo 1 (colunas)                                

[0 2 1 0]

[0 2 0]


---

# 2: array.argmin

In [6]:
arr2 = criar_array_aleatorio(3, 4)
arr2

array([[ 1,  6, 53, 98],
       [78, 64, 57,  2],
       [48, 43,  1, 79]])

In [7]:
# arr2.argmin(axis=0) = [indmin of column 0 | indmin of column 1 | indmin of column 2 | indmin of column 3]
# arr2.argmin(axis=1) = [indmin of row 0 | indmin of row 1 | indmin of row 2]

print(arr2.argmin(axis=0))
print()
print(arr2.argmin(axis=1))

[0 0 2 1]

[0 3 2]


---

# 3: array.argsort

In [8]:
# 3. argsort
arr3 = criar_array_aleatorio(2, 4)
arr3

array([[23, 78, 83, 65],
       [82, 60, 45, 39]])

In [9]:
# foi utilizado o ravel abaixo para retornar o array 'achatado' (1 dimensão). Isto é diferente de uma matriz 1x8 ou 8x1
arr3 = arr3.ravel()                # retorna o array 'achatado' (1 dimensão)
arr3

array([23, 78, 83, 65, 82, 60, 45, 39])

In [10]:
# oito elementos na única dimensão do array
arr3.shape

(8,)

In [12]:
arr3

array([23, 78, 83, 65, 82, 60, 45, 39])

In [11]:
# arr3.argsort() = [ indice do valor minimo  |  indice do 2nd valor minimo  |  indice do 3rd valor minimo  |  ...]
argsort = arr3.argsort()     # retorna os índices dos valores que classificariam o array
print(argsort)

[0 7 6 5 3 1 4 2]


In [20]:
# ranqueando o array (arr[4]) em ordem decrescente
arr[4][[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]]

array([50,  5, 20, 10, 30, 25, 40, 15, 35, 45])

In [21]:
# resultado do método argsort aplicado no objeto arr3
argsort

array([0, 7, 6, 5, 3, 1, 4, 2], dtype=int64)

In [24]:
# invertendo a ordem do resultado do argsort
argsort[::-1]

array([2, 4, 1, 3, 5, 6, 7, 0], dtype=int64)

In [23]:
arr3[argsort]                           # retorna o array classificado

array([23, 39, 45, 60, 65, 78, 82, 83])

In [26]:
arr3[argsort[::-1]]

array([83, 82, 78, 65, 60, 45, 39, 23])

In [ ]:
arr3 = criar_array_aleatorio(2, 4)
arr3

In [ ]:
arr3.argsort(axis=0)                    # retorna os indices que ordenariam o array considerando o eixo 0 (linhas)

In [ ]:
arr3.argsort(axis=1)                    # retorna os indices que ordenariam o array considerando o eixo 1 (colunas)

---

# 4: array.max

In [28]:
arr4 = criar_array_aleatorio(3, cols=4)
arr4

array([[82, 91, 79, 79],
       [68, 89, 83,  5],
       [68, 83, 91,  9]])

In [29]:
print(arr4.max())                   # retorna o valor máximo do array inteiro

91


In [30]:
print(arr4.max(axis=0))             # retorna o valor máximo do array considerando o eixo 0 (linhas)

[82 91 91 79]


In [31]:
print(arr4.max(axis=1))             # retorna o valor máximo do array considerando o eixo 1 (colunas)

[91 89 91]


---

# 5: array.min

In [32]:
arr5 = criar_array_aleatorio(3, 4)
arr5

array([[33, 53, 39, 15],
       [82, 82, 15, 83],
       [22, 45, 15, 51]])

In [33]:
print(arr5.min())                   # retorna o valor mínimo do array inteiro

15


In [34]:
print(arr5.min(axis=0))             # retorna o valor mínimo do array considerando o eixo 0 (linhas)

[22 45 15 15]


In [35]:
print(arr5.min(axis=1))             # retorna o valor mínimo do array considerando o eixo 1 (colunas)

[15 15 15]


---

# 6: array.mean

In [36]:
arr6 = criar_array_aleatorio(3, 4)
arr6

array([[46, 46, 33, 58],
       [99, 39, 90, 35],
       [67,  0, 21,  1]])

In [37]:
print(arr6.mean())                   # retorna a média do array inteiro

44.583333333333336


In [38]:
print(arr6.mean(axis=0))             # retorna a média do array considerando o eixo 0 (linhas)

[70.66666667 28.33333333 48.         31.33333333]


In [39]:
print(arr6.mean(axis=1))             # retorna a média do array considerando o eixo 1 (colunas)

[45.75 65.75 22.25]


---

# 7: array.std

In [40]:
arr7 = criar_array_aleatorio(3, 4)
arr7

array([[92, 75, 23, 77],
       [73, 15,  5, 18],
       [ 6, 42, 88,  6]])

In [41]:
print(arr7.std())                   # retorna o desvio padrão do array inteiro

33.536878540231235


In [42]:
print(arr7.std(axis=0))             # retorna o desvio padrão do array considerando o eixo 0 (linhas)

[36.88721549 24.53568829 35.64952859 31.03045099]


In [43]:
print(arr7.std(axis=1))             # retorna o desvio padrão do array considerando o eixo 1 (colunas)

[26.09956896 26.56477931 33.68605053]


In [44]:
# usando o método round no array que retornou do metodo 'std'
print(arr7.std(axis=1).round(1+1))

[26.1  26.56 33.69]


---

# 8: array.sum

In [46]:
arr8 = criar_array_aleatorio(3, 9)
arr8

array([[37,  5, 91,  8, 98, 82, 52, 73, 11],
       [ 5, 95, 65,  3, 18, 22, 47, 51, 18],
       [10, 32, 44, 17, 48, 39, 82, 20, 43]])

In [47]:
print(arr8.sum())                   # retorna a soma do array inteiro

1116


In [48]:
print(arr8.sum(axis=0))             # retorna a soma do array considerando o eixo 0 (linhas)

[ 52 132 200  28 164 143 181 144  72]


In [49]:
print(arr8.sum(axis=1))             # retorna a soma do array considerando o eixo 1 (colunas)

[457 324 335]


---

# 9: array.var

In [50]:
arr9 = criar_array_aleatorio(3, 4)
arr9

array([[12, 10, 93, 97],
       [ 8, 59, 68, 44],
       [46, 91, 56, 19]])

In [51]:
print(arr9.var())                   # retorna a variância do array inteiro

1000.0208333333334


In [52]:
print(arr9.var(axis=0))             # retorna a variância do array considerando o eixo 0 (linhas)

[ 290.66666667 1109.55555556  237.55555556 1057.55555556]


In [53]:
print(arr9.var(axis=1))             # retorna a variância do array considerando o eixo 1 (colunas)

[1766.5     523.6875  664.5   ]


---

# 10: array.reshape

In [54]:
# 10. array.reshape
arr10 = criar_array_aleatorio(3, 4)
arr10

array([[81,  9, 19, 58],
       [78, 34, 43, 30],
       [ 0, 25, 16, 35]])

In [59]:
# a quantidade e elementos do array deve ser a mesma após o reshape
print(arr10.reshape(4, 3))  # retorna o array com a nova forma (diferente de transpor o array)
print()
print(arr10.reshape(2, 6))  # retorna o array com a nova forma
print()
print(arr10.reshape(1, 12)) # retorna o array com a nova forma

[[81  9 19]
 [58 78 34]
 [43 30  0]
 [25 16 35]]

[[81  9 19 58 78 34]
 [43 30  0 25 16 35]]

[[81  9 19 58 78 34 43 30  0 25 16 35]]


In [61]:
arr8.reshape(1, np.multiply(*arr8.shape))

array([[37,  5, 91,  8, 98, 82, 52, 73, 11,  5, 95, 65,  3, 18, 22, 47,
        51, 18, 10, 32, 44, 17, 48, 39, 82, 20, 43]])

In [62]:
# retorna um outro array com uma linha e todos os outros elementos
# nas colunas 
arr8.reshape(1, -1)

array([[37,  5, 91,  8, 98, 82, 52, 73, 11,  5, 95, 65,  3, 18, 22, 47,
        51, 18, 10, 32, 44, 17, 48, 39, 82, 20, 43]])

In [63]:
arr8.reshape(-1, 1)

array([[37],
       [ 5],
       [91],
       [ 8],
       [98],
       [82],
       [52],
       [73],
       [11],
       [ 5],
       [95],
       [65],
       [ 3],
       [18],
       [22],
       [47],
       [51],
       [18],
       [10],
       [32],
       [44],
       [17],
       [48],
       [39],
       [82],
       [20],
       [43]])

In [66]:
(arr8.reshape(-1) == arr8.ravel()).all()

True

---

# 11: array.ravel

In [67]:
# 11. array.ravel
arr11 = criar_array_aleatorio(3, 4)
arr11

array([[53, 97, 98, 92],
       [84, 52,  3, 56],
       [24, 15, 98, 24]])

In [68]:
print(arr11.ravel())                 # returns a new array with the new shape

[53 97 98 92 84 52  3 56 24 15 98 24]


---
# Numpy Functions

In [ ]:
# existem 509 funções do pacote numpy
print(dir(np)[82:])

# 12: np.unique

In [71]:
# 12. np.unique
arr12 = criar_array_aleatorio(1, 50)
arr12

array([[54, 22, 74, 89, 75, 28, 70,  1, 29,  4, 56, 73, 43, 61, 32, 14,
        59, 13,  2, 83, 32, 95, 20, 56, 69, 35, 20, 85, 38, 91, 30, 14,
        49, 90, 13, 79,  1, 59, 63, 71, 85, 63, 54,  0, 41, 71, 57, 78,
        72, 22]])

In [72]:
type(np)

module

In [73]:
np.unique(arr12)         # remove os valores duplicados do array e classifica os valores

array([ 0,  1,  2,  4, 13, 14, 20, 22, 28, 29, 30, 32, 35, 38, 41, 43, 49,
       54, 56, 57, 59, 61, 63, 69, 70, 71, 72, 73, 74, 75, 78, 79, 83, 85,
       89, 90, 91, 95])

---

# 13: np.random.randint

In [86]:
# 13. np.random.randint
arr13 = np.random.randint(low=0, high=100, size=(3, 4))     # cria um array com dimensao 3x4 com valores aleatórios entre 0 e 100
arr13

array([[61, 69, 64, 90],
       [10, 59, 63, 42],
       [70, 82, 43, 10]])

In [91]:
# a primeira coluna vai ser entre 2 e 5 - 1 e a segunda coluna vai ser entre 3 e 10 - 1
# low das colunas e high das colunas
np.random.randint(low=[2, 3], high=[3, 10], size=(3, 2))  # mude os valores de low e high para ver o resultado

array([[2, 9],
       [2, 9],
       [2, 9]])

---

# 14: np.random.randn

In [92]:
# 14. np.random;randn
arr14 = np.random.randn(3, 4)     # cria um array que respeita a distribuição normal (gaussiana) com média 0 e desvio padrão 1
arr14

array([[ 0.83914177, -0.70638163, -0.59341855, -1.61294462],
       [ 1.71546176,  0.34713944,  1.49714078, -0.69338652],
       [ 0.47348011,  0.38027155,  1.03366572, -0.97566627]])

---

# 15: np.random.choice

In [95]:
# 15. np.random.choice
choice = np.random.choice([1, 2, 3, 4, 5, 6])                                # escolhe um elemento aleatório da lista
print(choice)

2


In [96]:
arr16 = np.random.choice([1, 2, 3, 4, 5, 6], size=3, replace=False)     # escolhe 3 elementos aleatórios da lista sem reposição
print(arr16)

[4 1 3]


In [97]:
arr17 = np.random.choice([1, 2, 3, 4, 5, 6], size=(3, 2), replace=True)                   # escolhe 6 elementos aleatórios da lista com reposição
print(arr17)

[[3 5]
 [1 3]
 [5 2]]


---

# 16: np.arange

In [98]:
print(np.arange(0, 10))         # mesmo que range(0, 10)

[0 1 2 3 4 5 6 7 8 9]


In [99]:
# o zero é inclusive, o 10 é exclusive e o 2 é o passo (inteiro)
print(np.arange(0, 10, 2))      # mesmo que range(0, 10, 2)

[0 2 4 6 8]


In [100]:
# o zero é inclusive, o 5 é exclusive e o 0.5 é o passo (float)
print(np.arange(0, 5, 0.5))     # assim não existe equivalencia com range

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


---

# 17: np.random.shuffle

In [104]:
# 17. np.random.shuffle (shuffle = embaralhar)
arr18 = np.arange(10)
print(arr18)
np.random.shuffle(arr18)            # embaralha o array inplace (não retorna nada)
print(arr18)

[0 1 2 3 4 5 6 7 8 9]
[4 6 9 8 1 7 0 2 3 5]


In [102]:
print(np.random.shuffle(arr18))

None


---

# 18: np.random.seed

In [106]:
# np.random.seed
np.random.seed(42)  # fixa a semente para que os números aleatórios sejam sempre os mesmos para um mesmo seed
arr19 = np.random.randint(0, 100, size=(3, 4))
arr19

array([[51, 92, 14, 71],
       [60, 20, 82, 86],
       [74, 74, 87, 99]])

---

# 19: np.concatenate

In [107]:
# 19. np.concatenate
arr20 = np.random.randint(0, 100, size=(3, 4))
arr21 = np.random.randint(0, 100, size=(7, 4))

In [108]:
arr20

array([[23,  2, 21, 52],
       [ 1, 87, 29, 37],
       [ 1, 63, 59, 20]])

In [109]:
arr21

array([[32, 75, 57, 21],
       [88, 48, 90, 58],
       [41, 91, 59, 79],
       [14, 61, 61, 46],
       [61, 50, 54, 63],
       [ 2, 50,  6, 20],
       [72, 38, 17,  3]])

In [110]:
# perceba que os arrays a serem concatenados devem ser passados dentro de uma lista
np.concatenate([arr20, arr21], axis=0)        # concatena verticalmente

array([[23,  2, 21, 52],
       [ 1, 87, 29, 37],
       [ 1, 63, 59, 20],
       [32, 75, 57, 21],
       [88, 48, 90, 58],
       [41, 91, 59, 79],
       [14, 61, 61, 46],
       [61, 50, 54, 63],
       [ 2, 50,  6, 20],
       [72, 38, 17,  3]])

---
# 20: np.where

In [111]:
arr22 = np.arange(5, 10)
arr22

array([5, 6, 7, 8, 9])

In [112]:
np.where(arr22 >= 7)                              # retorna os indices dos elementos que satisfazem a condição

(array([2, 3, 4], dtype=int64),)

In [113]:
res_where = np.where(arr22 >= 7, 'yes', 'no')   # insere nos indices que satisfazem a condição o valor 'yes' e nos demais o valor 'no'
res_where

array(['no', 'no', 'yes', 'yes', 'yes'], dtype='<U3')

In [114]:
arr23 = criar_array_aleatorio(3, 4)
arr23

array([[88, 59, 13,  8],
       [89, 52,  1, 83],
       [91, 59, 70, 43]])

In [121]:
for lin, col in zip(**np.where(arr23 > 50)):
    print(arr23[lin, col])

88
59
89
52
83
91
59
70


---
# np.linspace

In [120]:
np.linspace(0, 10, 50)       # retorna 5 elementos entre 0 e 10 (inclusive)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

---
# Operações com vetores (produto escalar e produto vetorial)

In [ ]:
arr23 = np.array([2, 4, 1])
arr24 = np.array([3, 0, 1])

In [ ]:
arr23 @ arr24                               # mesmo que np.dot(arr23, arr24) ou arr23.dot(arr24)

In [ ]:
np.cross(arr23, arr24)                      # produto vetorial

In [ ]:
np.cross(arr23, arr24)

In [ ]:
np.cross(arr23, arr24) ** 2

In [ ]:
(np.cross(arr23, arr24) ** 2).sum()

In [ ]:
(np.cross(arr23, arr24) ** 2).sum() ** (1/2)